DeepRec-AI/HybridBackend

docs/tutorials/data_loading.md, hybridbackend/cpp/tensorflow/ops/rebatch_dataset_ops.cc, hybridbackend/tensorflow/data/rebatch.py, hybridbackend/tensorflow/data/rebatch_dataset.py, hybridbackend/tensorflow/data/rebatch_dataset_v1.py, hybridbackend/tensorflow/data/rebatch_dataset_v2.py, setup.py, tests/tensorflow/data/parquet_dataset_benchmark.py, tests/tensorflow/data/parquet_dataset_rebatch_test.py
This PR introduces `hb.data.rebatch` for resizing batches from tabular data (#6).
**Example**:
```python
import tensorflow as tf
import hybridbackend.tensorflow as hb
ds = hb.data.ParquetDataset(filename, micro_batch_size)
ds = ds.apply(hb.data.rebatch(batch_size))
```
=> [IO] Add `hb.data.rebatch`.

.github/ISSUE_TEMPLATE/20-documentation.md, .github/workflows/cpu-legacy-nightly.yaml, .github/workflows/cpu-legacy.yaml, .github/workflows/cpu-nightly.yaml, .github/workflows/cpu.yaml, README.md
This patch separate release build and nightly build for more precise controlling of building scope.
=> [CI] Separate release build and nightly build.

CONTRIBUTING.md, README.md, arrow/build.sh, hybridbackend/tensorflow/training/__init__.py
This patch fixes arrow patching error and upgrades HybridBackend to v0.5.2.
=> [CI] Fix arrow patching and upgrade to v0.5.2.

.github/workflows/cpu-cibuild.yaml, .github/workflows/cpu-legacy-nightly.yaml, .github/workflows/cpu-legacy.yaml, .github/workflows/cpu-nightly.yaml, .github/workflows/cpu.yaml, .gitmodules, Makefile, cibuild/format, cibuild/lint, hybridbackend/cpp/common/env.cc, hybridbackend/cpp/common/env.h, hybridbackend/cpp/tensorflow/arrow/arrow.h, hybridbackend/cpp/tensorflow/arrow/parquet_batch_reader.h, hybridbackend/tensorflow/framework/context.py, hybridbackend/tensorflow/framework/device.py, hybridbackend/tensorflow/framework/scope.py, tests/tensorflow/data/parquet_dataset_ragged_test.py, tests/tensorflow/data/parquet_dataset_rebatch_test.py, tests/tensorflow/data/parquet_dataset_string_test.py, tests/tensorflow/data/parquet_dataset_test.py, tests/tensorflow/spawn.py
This PR:
1. Refine cibuild pipeline to support selective testing;
2. Add sparsehash dependency;
3. Tolerate broken `TF_CONFIG` in early version of kubeflow;
4. Add various utilities;
=> [CI] Refine cibuild and fix minor issues.

hybridbackend/tensorflow/ops/__init__.py, hybridbackend/tensorflow/ops/math_ops.py, hybridbackend/tensorflow/saved_model/__init__.py, hybridbackend/tensorflow/saved_model/builder.py, hybridbackend/tensorflow/saved_model/builder_impl.py, hybridbackend/tensorflow/saved_model/simple_save.py, hybridbackend/tensorflow/training/__init__.py, hybridbackend/tensorflow/training/optimizer.py, hybridbackend/tensorflow/training/optimizer_lib.py, hybridbackend/tensorflow/training/parallel_evaluation_hook.py, hybridbackend/tensorflow/training/saver.py, tests/tensorflow/training/optimizer_test.py
This PR adds support of hybrid-parallel training:
1. Supports training with both replicated variables and sharded variables;
2. Supports saving checkpoints in parallel;
3. Supports exporting to saved models in parallel;
4. Supports evaluate in parallel;
=> [DIST] Add support of hybrid-parallel training.

hybridbackend/tensorflow/feature_column/__init__.py, hybridbackend/tensorflow/feature_column/dense_features.py, hybridbackend/tensorflow/feature_column/embedding_backend.py, hybridbackend/tensorflow/feature_column/embedding_backend_default.py, hybridbackend/tensorflow/feature_column/embedding_lookup.py, hybridbackend/tensorflow/feature_column/embedding_lookup_buffered.py, hybridbackend/tensorflow/feature_column/embedding_lookup_coalesced.py, hybridbackend/tensorflow/feature_column/feature_column.py, hybridbackend/tensorflow/feature_column/raw_categorical_column.py, hybridbackend/tools/embedding_benchmark.py, tests/tensorflow/feature_column/dense_features_test.py
This PR supports sharded embedding variable via embedding column API. #37
=> [EMB] Add support of feature column API.

hybridbackend/tensorflow/metrics/__init__.py, hybridbackend/tensorflow/metrics/accuracy.py, hybridbackend/tensorflow/metrics/auc.py, hybridbackend/tensorflow/metrics/mean.py
This patch introduces common evaluation metrics such as auc and accuracy
=> [DIST] Add common evaluation metrics.

hybridbackend/cpp/tensorflow/arrow/arrow.cc, hybridbackend/cpp/tensorflow/arrow/arrow.h, hybridbackend/cpp/tensorflow/arrow/parquet_batch_reader.cc, hybridbackend/cpp/tensorflow/arrow/parquet_batch_reader.h, hybridbackend/cpp/tensorflow/ops/parquet_dataset_ops.cc, hybridbackend/cpp/tensorflow/ops/rebatch_dataset_ops.cc, hybridbackend/tensorflow/data/dataframe.py, hybridbackend/tensorflow/data/parquet_dataset_reshape_test.py, hybridbackend/tensorflow/data/parquet_dataset_v1.py, hybridbackend/tensorflow/data/parquet_dataset_v2.py, hybridbackend/tensorflow/data/parquet_validate.py, hybridbackend/tensorflow/data/rebatch_dataset_test.py
=> [DATA] Fix fixed-length list support

hybridbackend/tensorflow/data/common/arrow.cc, hybridbackend/tensorflow/data/dataframe.py, hybridbackend/tensorflow/data/tests/parquet_dataset_ragged_nested_test.py
=> [Data] Fix nested list support

docs/tutorial/ranking/criteo/train_keras.py, docs/tutorial/ranking/taobao/train_keras.py, hybridbackend/tensorflow/keras/model.py, hybridbackend/tensorflow/training/saver.py
This patch closes #81 #82 
1) Support loading weights by name with options of skipping mismatched variables.
2) Support using functional API to create `hb.keras.Model`.
3) Multiple other supports such as using `tf.data.Dataset` as arguments in `model.fit`.
=> [DIST] Support loading weights and Functional API in Keras.

docs/tutorial/ranking/criteo/train_keras.py, hybridbackend/tensorflow/keras/model.py
1. Support printing info when loading weights in Keras. a. the ratio of filtered variables by the `scope` arguments of `model.load_weights` is print. b. the ratio of loading variables that hits the ckpt is print. #86 
2. Support the usage of multiple labels and nested metrics in hb.keras. #85 #90 
3. Support printing layer's info in Keras. #87
=> [DIST] Multiple enhancement in `hb.keras`. 

.github/workflows/cibuild.yaml, hybridbackend/tensorflow/training/__init__.py, hybridbackend/tensorflow/training/sync_replicas_optimizer.py
This patch supports sync training of imbalanced data across devices in SyncReplicasOptimizer, fixes #96
=> [DIST] Support sync training of imbalanced data across devices

docs/tutorial/ranking/criteo/train_semi_sync.py, docs/tutorial/ranking/taobao/train_semi_sync.py, hybridbackend/tensorflow/__init__.py, hybridbackend/tensorflow/pipeline/__init__.py, hybridbackend/tensorflow/pipeline/benchmark.py, hybridbackend/tensorflow/pipeline/pipeline_lib.py
1. Use `data_batch_count` within hb.scope() to support multiple micro batches in sem-sync training.
2. Use the function annotation `hb.pipeline.compute_pipeline` to mark the function that computes a loss from inputs.
=> [DIST] Support pipeline-based semi-synchronous training.

docs/tutorial/ranking/criteo/train_estimator.py, docs/tutorial/ranking/taobao/train_estimator.py, hybridbackend/tensorflow/estimator/estimator.py
Support the usage of estimator's evaluate and predict methods.
=> [DIST] Support standalone evaluation and prediction in `hb.Estimator`. 

docs/tutorial/ranking/criteo/train_keras.py, hybridbackend/tensorflow/embedding/sharding.py
1. patching shared embedding get_shape method by using TensorShape to be compatible with init_from_checkpoint.
2. patching the `get_shape` method of embeddings created by `tf.contrib.feature_column` API in distributed training.
#122
=> [DIST] Fix: Shared embedding shape rewriting.

docs/tutorial/ranking/criteo/train_keras.py, docs/tutorial/ranking/taobao/train_keras.py, hybridbackend/tensorflow/keras/model.py
1. support a standalone usage of `evaluate` method in `hb.keras`.
=> [DIST] Support a standalone evaluation in `hb.keras`.

docs/tutorial/ranking/criteo/train.py, docs/tutorial/ranking/criteo/train_semi_sync.py, docs/tutorial/ranking/taobao/train.py, docs/tutorial/ranking/taobao/train_estimator.py, docs/tutorial/ranking/taobao/train_keras_din.py, docs/tutorial/ranking/taobao/train_semi_sync.py, hybridbackend/tensorflow/embedding/deeprecev.py, hybridbackend/tensorflow/training/optimizer.py, hybridbackend/tensorflow/training/saver.py
1. Make EV variables of deeprec to use variable_scope + partitioner for sharding.
=> [DIST] Use variable_scope with partitioner for sharded deeprecev.

hybridbackend/tensorflow/benchmarks/transfer_benchmark.py, hybridbackend/tensorflow/graph/common/fusion.cc, hybridbackend/tensorflow/graph/common/fusion.h, hybridbackend/tensorflow/graph/common/pruning.cc, hybridbackend/tensorflow/graph/common/pruning.h
This patch introduces automatic optimization of transfers.
=> [DATA] Support transfer optimization

hybridbackend/tensorflow/data/iterators.py
Rewrite NanTensorHook to be compatible with the returned empty tensor from SyncReplicasDataset.
=> [DIST] Rewrite NanTensorHook for SyncReplicasDataset.

docs/tutorial/ranking/criteo/train.py, docs/tutorial/ranking/taobao/train.py, hybridbackend/tensorflow/data/__init__.py, hybridbackend/tensorflow/data/tests/sync_replicas_dataset_test.py, hybridbackend/tensorflow/estimator/estimator.py, hybridbackend/tensorflow/keras/model.py
1. set data_sync_drop_remainder to true by default.
=> [DIST] Set data_sync_drop_remainder as true by default.

docs/data.md, docs/distributed.md, docs/high_level_api.md
1. data deduplication. 2 the usage of `hb.embedding_scope`
3. DataSyncReplicas
4. `hb.keras` API.
=> [DOC] Add user docs for data deduplication and so forth.
